[project]
name = 'Cosmic-Anomaly-Detection'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.anomaly-nft]
path = 'contracts/anomaly-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.anomaly-reporting]
path = 'contracts/anomaly-reporting.clar'
clarity_version = 2
epoch = 2.5

[contracts.collaborative-research]
path = 'contracts/collaborative-research.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
